var searchData=
[
  ['definitions_20for_20the_20alert_20level_20characteristic_20values',['Definitions for the Alert Level characteristic values',['../group___a_l_e_r_t___l_e_v_e_l___v_a_l_u_e_s.html',1,'']]],
  ['defines',['Defines',['../../s132/group___b_l_e___c_o_m_m_o_n___d_e_f_i_n_e_s.html',1,'']]],
  ['database_20discovery',['Database Discovery',['../group__ble__db__discovery.html',1,'']]],
  ['database_20discovery_20module_20configuration',['Database discovery module configuration',['../group__ble__db__discovery__config.html',1,'']]],
  ['device_20information_20service',['Device Information Service',['../group__ble__dis.html',1,'']]],
  ['device_20information_20service_20configuration',['Device Information Service configuration',['../group__ble__dis__config.html',1,'']]],
  ['dtm_20_2d_20direct_20test_20mode',['DTM - Direct Test Mode',['../group__ble__dtm.html',1,'']]],
  ['dtm_20application_20command_20request_20encoders_20and_20command_20response_20decoders',['DTM Application command request encoders and command response decoders',['../group__ble__dtm__app.html',1,'']]],
  ['dtm_20connectivity_20command_20request_20decoder_20and_20command_20response_20encoder',['DTM Connectivity command request decoder and command response encoder',['../group__ble__dtm__conn.html',1,'']]],
  ['direct_20test_20mode_20hw',['Direct Test Mode HW',['../group__ble__dtm__hw.html',1,'']]],
  ['defines',['Defines',['../../s132/group___b_l_e___g_a_p___d_e_f_i_n_e_s.html',1,'']]],
  ['directed_20advertising',['Directed Advertising',['../../s132/group___b_l_e___g_a_p___p_r_i_v_a_c_y___a_d_v___d_i_r___p_r_i_v___m_s_c.html',1,'']]],
  ['defines',['Defines',['../../s132/group___b_l_e___g_a_t_t___d_e_f_i_n_e_s.html',1,'']]],
  ['defines',['Defines',['../../s132/group___b_l_e___g_a_t_t_c___d_e_f_i_n_e_s.html',1,'']]],
  ['defines',['Defines',['../../s132/group___b_l_e___g_a_t_t_s___d_e_f_i_n_e_s.html',1,'']]],
  ['defines',['Defines',['../../s132/group___b_l_e___l2_c_a_p___d_e_f_i_n_e_s.html',1,'']]],
  ['defines',['Defines',['../../s132/group___b_l_e___t_y_p_e_s___d_e_f_i_n_e_s.html',1,'']]],
  ['dynamic_20memory_20allocator_20configuration',['Dynamic memory allocator configuration',['../group__mem__manager__config.html',1,'']]],
  ['dfu_20ble_20service',['DFU BLE Service',['../group__nrf__ble__dfu.html',1,'']]],
  ['dfu_20settings',['DFU settings',['../group__nrf__dfu__settings.html',1,'']]],
  ['ds1624_20digital_20temperature_20sensor_20driver',['DS1624 digital temperature sensor driver',['../group__nrf__drivers__ds1624.html',1,'']]],
  ['driver_20for_20adc_20peripheral_20_28nrf51_29_20configuration',['Driver for ADC peripheral (nRF51) configuration',['../group__nrf__drv__adc__config.html',1,'']]],
  ['defines',['Defines',['../../s132/group___n_r_f___m_b_r___d_e_f_i_n_e_s.html',1,'']]],
  ['defines',['Defines',['../../s132/group___n_r_f___n_v_i_c___d_e_f_i_n_e_s.html',1,'']]],
  ['defines',['Defines',['../../s132/group___n_r_f___s_d_m___d_e_f_i_n_e_s.html',1,'']]],
  ['defines',['Defines',['../../s132/group___n_r_f___s_o_c___d_e_f_i_n_e_s.html',1,'']]],
  ['dfu_20bootloader',['DFU bootloader',['../group__sdk__nrf__dfu.html',1,'']]],
  ['dfu_20transport',['DFU transport',['../group__sdk__nrf__dfu__transport.html',1,'']]],
  ['dfu_20types',['DFU types',['../group__sdk__nrf__dfu__types.html',1,'']]],
  ['dfu_20utilities',['DFU utilities',['../group__sdk__nrf__dfu__utils.html',1,'']]],
  ['dtm_20command_20decoder_20in_20the_20connectivity_20chip',['DTM Command Decoder in the Connectivity Chip',['../group__ser__dtm__decoder.html',1,'']]]
];
