var searchData=
[
  ['sd_20card_20example',['SD Card Example',['../app_sdcard_example.html',1,'examples_hw_peripheral_devices']]],
  ['saadc',['SAADC',['../hardware_driver_saadc.html',1,'hardware_drivers']]],
  ['spi_20master',['SPI master',['../hardware_driver_spi_master.html',1,'hardware_drivers']]],
  ['spi_20slave',['SPI slave',['../hardware_driver_spi_slave.html',1,'hardware_drivers']]],
  ['swi',['SWI',['../hardware_driver_swi.html',1,'hardware_drivers']]],
  ['s132_20softdevice_20v3_2e0_2e0_20api',['S132 SoftDevice v3.0.0 API',['../../s132/index.html',1,'(Global Namespace)'],['../../s130/index.html',1,'(Global Namespace)'],['../../s212/index.html',1,'(Global Namespace)'],['../../s332/index.html',1,'(Global Namespace)']]],
  ['storage_20format',['Storage format',['../lib_fds_format.html',1,'lib_fds']]],
  ['schedule_20handling_20library',['Schedule handling library',['../lib_scheduler.html',1,'general_libraries']]],
  ['sd_20card_20library',['SD card library',['../lib_sdcard.html',1,'general_libraries']]],
  ['sensor_20data_20simulator',['Sensor Data Simulator',['../lib_sensorsim.html',1,'general_libraries']]],
  ['sha_2d256_20hash_20computation',['SHA-256 hash computation',['../lib_sha256.html',1,'general_libraries']]],
  ['simple_20timer',['Simple timer',['../lib_simple_timer.html',1,'general_libraries']]],
  ['slip_20handling_20library',['SLIP handling library',['../lib_slip.html',1,'transport_libraries']]],
  ['softdevice_20handler_20library',['SoftDevice handler library',['../lib_softdevice_handler.html',1,'general_libraries']]],
  ['saadc_20example',['SAADC Example',['../nrf_dev_saadc_example.html',1,'examples_hw_peripheral_devices']]],
  ['simple_20timer_20example',['Simple Timer Example',['../nrf_dev_simple_timer_example.html',1,'examples_hw_peripheral_devices']]],
  ['stride_20based_20speed_20and_20distance_20monitor',['Stride Based Speed and Distance Monitor',['../profile_ant_sdm.html',1,'lib_ant_profiles']]],
  ['sdk_20configuration_20header_20file',['SDK configuration header file',['../sdk_config.html',1,'nrf51_getting_started']]],
  ['spi_5f5w_20raw_20protocol',['SPI_5W RAW protocol',['../ser_phy_spi_5_w_page.html',1,'serialization_phy']]],
  ['spi_20raw_20protocol',['SPI RAW protocol',['../ser_phy_spi_page.html',1,'serialization_phy']]],
  ['serialization_20codecs',['Serialization Codecs',['../serialization_codecs.html',1,'lib_serialization']]],
  ['serialization_20phy',['Serialization PHY',['../serialization_phy.html',1,'lib_serialization']]],
  ['serialization_20hal_20transport',['Serialization HAL Transport',['../serialization_transport.html',1,'lib_serialization']]],
  ['spi_20master_20example',['SPI Master Example',['../spi_master_example.html',1,'examples_hw_peripheral_devices']]],
  ['spi_20slave_20example',['SPI Slave Example',['../spi_slave_example.html',1,'examples_hw_peripheral_devices']]]
];
