var group__app__common =
[
    [ "GATT Database Service Structure", "group__ble__sdk__lib__gatt__db.html", "group__ble__sdk__lib__gatt__db" ],
    [ "Atomic FIFO implementation", "group__app__atfifo.html", "group__app__atfifo" ],
    [ "Block memory allocator", "group__nrf__balloc.html", "group__nrf__balloc" ],
    [ "Block device", "group__nrf__block__dev.html", "group__nrf__block__dev" ],
    [ "Bootloader modules", "group__sdk__nrf__bootloader.html", "group__sdk__nrf__bootloader" ],
    [ "Board Support Package", "group__bsp.html", "group__bsp" ],
    [ "Button Handler", "group__app__button.html", "group__app__button" ],
    [ "Cryptography library", "group__nrf__crypto.html", "group__nrf__crypto" ],
    [ "Capacitive Sensor Library", "group__nrf__csense.html", "group__nrf__csense" ],
    [ "Capacitive sensor support", "group__nrf__drv__csense.html", "group__nrf__drv__csense" ],
    [ "Elliptic Curve Cryptography interface", "group__ecc.html", "group__ecc" ],
    [ "Eddystone library", "group__eddystone.html", "group__eddystone" ],
    [ "Section variables", "group__section__vars.html", "group__section__vars" ],
    [ "Flash Data Storage", "group__fds.html", "group__fds" ],
    [ "FIFO implementation", "group__app__fifo.html", "group__app__fifo" ],
    [ "fstorage", "group__fstorage.html", "group__fstorage" ],
    [ "GPIOTE Handler", "group__app__gpiote.html", "group__app__gpiote" ],
    [ "HardFault exception", "group__hardfault__default.html", "group__hardfault__default" ],
    [ "Memory pool", "group__hci__mem__pool.html", "group__hci__mem__pool" ],
    [ "SLIP module", "group__hci__slip.html", "group__hci__slip" ],
    [ "HCI Transport", "group__hci__transport.html", "group__hci__transport" ],
    [ "IC information", "group__nrf__ic__info.html", "group__nrf__ic__info" ],
    [ "LED softblink", "group__led__softblink.html", "group__led__softblink" ],
    [ "Logger module", "group__nrf__log.html", "group__nrf__log" ],
    [ "Low-power PWM", "group__low__power__pwm.html", "group__low__power__pwm" ],
    [ "Mailbox library", "group__app__mailbox.html", "group__app__mailbox" ],
    [ "Memory Manager", "group__mem__manager.html", "group__mem__manager" ],
    [ "Pulse-width modulation (PWM)", "group__app__pwm.html", "group__app__pwm" ],
    [ "Power management", "group__nrf__pwr__mgmt.html", "group__nrf__pwr__mgmt" ],
    [ "Queue module", "group__nrf__queue.html", "group__nrf__queue" ],
    [ "Scheduler", "group__app__scheduler.html", "group__app__scheduler" ],
    [ "SD card library", "group__app__sdcard.html", "group__app__sdcard" ],
    [ "SHA-256 hash library", "group__sha256.html", "group__sha256" ],
    [ "Simple Timer", "group__app__simple__timer.html", "group__app__simple__timer" ],
    [ "SLIP encoding decoding", "group__slip.html", "group__slip" ],
    [ "Application Timer", "group__app__timer.html", "group__app__timer" ],
    [ "TWI transaction manager", "group__app__twi.html", "group__app__twi" ],
    [ "UART module", "group__app__uart.html", "group__app__uart" ],
    [ "USB Device high level library", "group__app__usbd.html", "group__app__usbd" ],
    [ "Common application error handler", "group__app__error.html", "group__app__error" ],
    [ "Utility Functions and Definitions", "group__app__util.html", "group__app__util" ],
    [ "Utility Functions and Definitions (Platform)", "group__app__util__platform.html", "group__app__util__platform" ],
    [ "SDK Error codes", "group__sdk__error.html", "group__sdk__error" ],
    [ "SDK Common Header", "group__sdk__common__macros.html", "group__sdk__common__macros" ],
    [ "Mapped flags", "group__sdk__mapped__flags.html", "group__sdk__mapped__flags" ],
    [ "SoftDevice Event Handler", "group__softdevice__handler.html", "group__softdevice__handler" ],
    [ "Retarget layer for stdio functions", "group__retarget.html", "group__retarget" ],
    [ "Adafruit PN532 NFC Shield library", "group__adafruit__pn532.html", "group__adafruit__pn532" ]
];